name: Build RC packages

name: Verify Integration Tests

on:
  pull_request:
    types: [labeled]

jobs:
  consumer-integration:
    if: github.event.label.name == 'verify'
    uses: agim89/shared-workflows/.github/workflows/consumer-verify.yml@main
    with:
      version: 1.2.0
      remote: conan-rc
    secrets: inherit